name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Bước 1: Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Bước 2: Cài đặt Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Bước 3: Cấu hình Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          version: latest

      # Bước 4: Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Bước 5: Đăng nhập vào Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bước 6: Build và push Docker image
      - name: Build and push Docker images
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          docker-compose -f docker-compose.yml build --build-arg BUILDKIT_INLINE_CACHE=1
          docker-compose -f docker-compose.yml push fastapi-backend
        continue-on-error: false

      # Bước 7: Deploy lên server
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd fastapi-project
            ls -la
            echo "${{ secrets.DOCKER_COMPOSE_FILE }}" > docker-compose.yml
            docker-compose config || { echo "Error in Docker Compose file:"; docker-compose config; exit 1; }
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            docker-compose pull
            docker ps -a --filter "name=fastapi-backend" --format '{{.ID}}' | xargs -r docker stop || true
            docker ps -a --filter "name=fastapi-backend" --format '{{.ID}}' | xargs -r docker rm || true
            docker-compose up -d
            docker image prune -f
            timeout 60 bash -c '
              until docker-compose ps | grep "Up"; do
                echo "Waiting for containers to start...";
                sleep 5;
              done
            ' || exit 1

      # Bước 8: Dọn dẹp
      - name: Cleanup
        if: always()
        run: |
          docker logout
          rm -rf /tmp/.buildx-cache